### ISSUE TITLE
Slack script fails

### ISSUE THREAD

**Issue by WouterKoch** [Artsdatabanken/ai#7]
.github/workflows)/slack.sh fails, seems to be a missing or incorrect secret.

Called as 
`run: .github/workflows/slack.sh ${{ secrets.POST_SLACK }}`
gives
`curl: (3) URL using bad/illegal format or missing URL`

See https://github.com/Artsdatabanken/ai/runs/5126524745?check_suite_focus=true'

**Comment by Myrdrahl** [comment]
Slack bestemte seg for å slette noen apps i vår workspace mens jeg lå nede for telling. Har oppdatert secrets og det ser ut til å virke nå.
